version: '3.8'

services:


  mongo:
    image: mongo
    container_name: test-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=qwerty
      - ME_CONFIG_MONGODB_URL=mongodb://root:qwerty@mongo:27017/
    depends_on:
      - mongo
  medods:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medods
    ports:
      - '8080:8080'
    depends_on:
      - mongo
